- name: Make sure required packages are installed
  hosts: all
  tasks:

- name: Install Docker on Rocky Linux 9
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      dnf:
        name:
          - dnf-utils
          - net-tools
          - zip
          - unzip
          - ftp
          - wget
          - git
          - xauth
          - xterm
          - nfs-utils
          - epel-release
          - tcpdump
          - chrony
          - rsyslog
          - python3
        state: present

    # - name: Add Docker repository
    #   command: >
    #     dnf config-manager
    #     --add-repo
    #     https://download.docker.com/linux/centos/docker-ce.repo

    - name: Add Docker repository
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Repository
        file: docker-ce
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes