---
- name: Temporarily enable passwordless sudo for engineer
  hosts: all
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Backup current sudoers file
      command: cp /etc/sudoers /etc/sudoers.bak
      become: no
      vars:
        ansible_become_pass: "{{ root_password }}"
      command: >
        su -c "cp /etc/sudoers /etc/sudoers.bak" root

    - name: Add engineer to sudoers with NOPASSWD
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^engineer'
        line: 'engineer ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: no
      vars:
        ansible_become_pass: "{{ root_password }}"
      command: >
        su -c "echo 'engineer ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers" root

- name: Install Docker on Rocky Linux 9
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      dnf:
        name:
          - dnf-utils
          - net-tools
          - zip
          - unzip
          - ftp
          - wget
          - git
          - xauth
          - xterm
          - yum-utils
          - nfs-utils
          - epel-release
          - tcpdump
          - chrony
          - rsyslog
          - python3
        state: present

    - name: Add Docker repository
      command: >
        dnf config-manager
        --add-repo
        https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Revert sudoers file to original state
  hosts: all
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Restore original sudoers file
      command: mv /etc/sudoers.bak /etc/sudoers
      become: no
      vars:
        ansible_become_pass: "{{ root_password }}"
      command: >
        su -c "mv /etc/sudoers.bak /etc/sudoers" root
