- name: Temporarily enable passwordless sudo for engineer
  hosts: all
  tasks:
    - name: Backup current sudoers file
      ansible.builtin.expect:
        command: su -c "cp /etc/sudoers /etc/sudoers.bak"
        responses:
          Password: "{{ root_password }}"

    - name: Add engineer to sudoers with NOPASSWD
      ansible.builtin.expect:
        command: su -c "{{ command }}"
        responses:
          Password: "{{ root_password }}"