---
- name: Install Docker on Rocky Linux 9
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      dnf:
        name:
          - dnf-utils
          - net-tools
          - zip
          - unzip
          - ftp
          - wget
          - git
          - xauth
          - xterm
          - nfs-utils
          - epel-release
          - tcpdump
          - chrony
          - rsyslog
          - python3
        state: present
      become: yes

    - name: Add Docker repository
      command: >
        dnf config-manager
        --add-repo
        https://download.docker.com/linux/centos/docker-ce.repo
      become: yes

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      become: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
