- name: Add user 'engineer' to sudoers using su with expect
  hosts: all
  tasks:
    - name: Create the script to add engineer to sudoers
      ansible.builtin.copy:
        dest: /tmp/add_engineer_to_sudoers.sh
        content: |
          #!/bin/bash

          # Check if the line already exists
          grep -q "^engineer ALL=(ALL) ALL" /etc/sudoers
          if [ $? -ne 0 ]; then
            echo "" >> /etc/sudoers
            echo "# Allow engineer user to run any commands as any user" >> /etc/sudoers
            echo "engineer ALL=(ALL) ALL" >> /etc/sudoers
          fi
        mode: '0755'

    - name: Switch to root and run the script
      ansible.builtin.expect:
        command: su -c "/tmp/add_engineer_to_sudoers.sh"
        responses:
          Password: "{{ root_password }}"
