- name: Temporarily enable passwordless sudo for engineer
  hosts: all
  become: yes
  tasks:
    - name: Backup current sudoers file
      ansible.builtin.expect:
        command: su -c "cp /etc/sudoers /etc/sudoers.bak" root
        responses:
          Password: "{{ root_password }}"

    - name: Add engineer to sudoers with NOPASSWD
      ansible.builtin.expect:
        command: su -c "{{ command }}" root
        responses:
          Password: "{{ root_password }}"