- name: Make sure required packages are installed
  hosts: all
  tasks:

- name: Install Docker on Rocky Linux 9
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      dnf:
        name:
          - dnf-utils
          - net-tools
          - zip
          - unzip
          - ftp
          - wget
          - git
          - xauth
          - xterm
          - nfs-utils
          - epel-release
          - tcpdump
          - chrony
          - rsyslog
          - python3
        state: present

    - name: Check if Docker repo file exists
      ansible.builtin.stat:
        path: /etc/yum.repos.d/docker-ce.repo
      register: repo_file

    - name: Download Docker repo file if it does not exist
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      when: not repo_file.stat.exists

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
    
    - name: Enable and start cockpit.socket
      ansible.builtin.systemd:
        name: cockpit.socket
        enabled: yes
        state: started