- name: Temporarily enable passwordless sudo for engineer
  hosts: all
  become: yes
  tasks:
    - name: Backup current sudoers file
      ansible.builtin.expect:
        command: su -c "cp /etc/sudoers /etc/sudoers.bak" root
        responses:
          Password: "{{ root_password }}"
      become: no

    - name: Add engineer to sudoers with NOPASSWD
      ansible.builtin.expect:
        command: su -c "{{ command }}" root
        responses:
          Password: "{{ root_password }}"
      become: no

- name: Install Docker on Rocky Linux 9
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      dnf:
        name:
          - dnf-utils
          - net-tools
          - zip
          - unzip
          - ftp
          - wget
          - git
          - xauth
          - xterm
          - nfs-utils
          - epel-release
          - tcpdump
          - chrony
          - rsyslog
          - python3
        state: present

    - name: Add Docker repository
      command: >
        dnf config-manager
        --add-repo
        https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Revert sudoers file to original state
  hosts: all
  become: yes
  tasks:
    - name: Restore original sudoers file
      ansible.builtin.expect:
        command: su -c "mv /etc/sudoers.bak /etc/sudoers" root
        responses:
          Password: "{{ root_password }}"
      become: no
