---
- name: Configure XOS Management bond
  hosts: all
  become: yes
  vars:
    interface: "ens224"
    connection_old: "Wired connection 1"
    connection_new: "Connection-BE"
    connection_mgmt: "Connection_MGMT"
    subnet: "10.70.77.0/24"
  tasks:
    - name: Check if the new connection exists
      command: nmcli connection show "{{ connection_new }}"
      register: new_connection
      ignore_errors: yes

    - name: Check if the old connection exists
      command: nmcli connection show "{{ connection_old }}"
      register: old_connection
      ignore_errors: yes

    - name: Set the connection variable if old connection is found
      set_fact:
        connection: "{{ connection_old }}"
      when: old_connection.rc ==0

    - name: Set the connection variable if new connection is found
      set_fact:
        connection: "{{ connection_new }}"
      when: new_connection.rc ==0

    - name: Debug connection variable
      debug:
        var: connection

    - name: Check IP configuration of management interface
      shell: |
        ip_addr=$(nmcli -t -f IP4.ADDRESS dev show | grep 10.17 | cut -d: -f2)
        echo -e "IP_ADDR=$ip_addr"
      register: network_info

    - name: Debug network info output
      debug:
        var: network_info

    - name: Set variables from the network info
      set_fact:
        ip_addr: "{{ network_info.stdout_lines[0].split('=')[1] | default('') }}"

    - name: Fail if any network variable is empty
      fail:
        msg: "One or more network variables are empty. Please check the network configuration."
      when: ip_addr == ''


    - name: Extract last octet of management interface IP
      set_fact:
        subnet_first_3_octet: "{{ subnet | regex_replace('.0/.*', '') }}"
        last_octet: "{{ ip_addr | regex_replace('.*\\.', '') | regex_replace('/.*', '') }}"

    - name: Print first three octets and last octet
      debug:
        msg: |
          "First three octets {{ subnet_first_3_octet }}""
          "Last octet of management interface IP is {{ last_octet }}"

    - name: Configure BE
      shell: |
        nmcli con mod {{ connection }} ipv4.addresses {{ subnet_first_3_octet }}.{{ last_octet }}/24 
        nmcli con mod {{ connection }} ipv4.method manual
        nmcli con mod {{ connection }} ipv6.method disabled
        nmcli con mod {{ connection }} connection.id {{ connection_new }}
        nmcli con up {{ connection }}
      args:
        executable: /bin/bash

    - name: Restart NetworkManager service
      systemd:
        name: NetworkManager
        state: restarted
