- name: Make sure required packages are installed
  hosts: all
  become: yes
  tasks:
    - name: Install expect package
      ansible.builtin.package:
        name: expect
        state: present

    - name: Run vosctl sh and execute command inside the container
      expect:
        command: vosctl sh
        responses:
          '.*root@vosflex.*': 'rm -f /var/lib/persistent/licensing/new_iso_install\n'
      register: result

    - name: Display output
      debug:
        msg: "{{ result.stdout }}"