- name: Make sure required packages are installed
  hosts: all
  tasks:

    - name: Comment lines starting with "metalink" in epel.repo
      lineinfile:
        path: /etc/yum.repos.d/epel.repo
        regexp: '^metalink'
        state: absent
        backrefs: yes
      notify:
        - restart yum

    - name: Uncomment lines starting with "#baseurl" in epel.repo
      replace:
        path: /etc/yum.repos.d/epel.repo
        regexp: '^#baseurl'
        replace: 'baseurl'
      notify:
        - restart yum

    - name: Replace URL in baseurl
      replace:
        path: /etc/yum.repos.d/epel.repo
        regexp: 'https://download.example/pub/'
        replace: 'http://mirror.fcix.net.proxy.alrawabi.local/'
      notify:
        - restart

  handlers:
    - name: restart yum
      service:
        name: yum
        state: restarted