- name: Make sure required packages are installed
  hosts: all
  become: yes
  vars:
    epel_files:
      - /etc/yum.repos.d/epel.repo
    repo_files:
      - /etc/yum.repos.d/epel.repo
      - /etc/yum.repos.d/rocky.repo
      - /etc/yum.repos.d/rocky-extras.repo
      - /etc/yum.repos.d/rocky-addons.repo
    rocky_repo_files:
      - /etc/yum.repos.d/rocky.repo
      - /etc/yum.repos.d/rocky-extras.repo
      - /etc/yum.repos.d/rocky-addons.repo
  tasks:

    - name: Comment lines starting with "mirrorlist" in repo files
      replace:
        path: "{{ item }}"
        regexp: '^#mirrorlist'
        replace: 'mirrorlist'
      with_items: "{{ repo_files }}"

    - name: Uncomment lines starting with "#baseurl" in repo files
      replace:
        path: "{{ item }}"
        regexp: '^baseurl'
        replace: '#baseurl'
      with_items: "{{ repo_files }}"

    - name: Replace URL in baseurl in rocky repo files
      replace:
        path: "{{ item }}"
        regexp: 'http://dl.rockylinux.org.proxy.alrawabi.local/'
        replace: 'http://dl.rockylinux.org/'
      with_items: "{{ rocky_repo_files }}"

    - name: Replace URL in baseurl in "epel.repo"
      replace:
        path: /etc/yum.repos.d/epel.repo
        regexp: 'http://mirror.fcix.net.proxy.alrawabi.local/'
        replace: 'http://mirror.fcix.net/'
      with_items: "{{ repo_files }}"

    - name: Uncomment lines starting with "#baseurl" in repo files
      replace:
        path: "{{ item }}"
        regexp: '^#baseurl'
        replace: 'baseurl'
      with_items: "{{ epel_files }}"