---
- name: Configure network interfaces
  hosts: all
  become: yes
  tasks:
    - name: Get the IP address of eno8303
      shell: |
        ip -4 addr show eno8303 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
      register: ip_address

    - name: Save the IP address to a variable
      set_fact:
        eno8303_ip: "{{ ip_address.stdout }}"

    - name: Remove eno8303 configuration from /etc/network/interfaces
      lineinfile:
        path: /etc/network/interfaces
        regexp: '^(iface|allow-hotplug) eno8303'
        state: absent

    - name: Check if bond-MGMT connection exists
      command: nmcli connection show bond-MGMT
      register: bond_check
      ignore_errors: yes

    - name: Create bond connection if not exists
      nmcli:
        conn_name: bond-MGMT
        ifname: bond0
        type: bond
        mode: active-backup
        ip4: "{{ eno8303_ip }}/24"
        gw4: 10.17.5.254
        dns4: 10.17.5.240
        dns4_search: alrawabi.local
      when: bond_check.rc != 0

    - name: Check if eno8303-slave connection exists
      command: nmcli connection show eno8303-slave
      register: eno8303_slave_check
      ignore_errors: yes

    - name: Add eno8303 to bond if not exists
      nmcli:
        conn_name: eno8303-slave
        ifname: eno8303
        type: ethernet
        master: bond0
      when: eno8303_slave_check.rc != 0

    - name: Check if eno8403-slave connection exists
      command: nmcli connection show eno8403-slave
      register: eno8403_slave_check
      ignore_errors: yes

    - name: Add eno8403 to bond if not exists
      nmcli:
        conn_name: eno8403-slave
        ifname: eno8403
        type: ethernet
        master: bond0
      when: eno8403_slave_check.rc != 0

    - name: Bring up the bond connection
      nmcli:
        conn_name: bond-MGMT
        state: up