---
- name: Download, extract, and install RPM files
  hosts: all
  become: yes
  tasks:
    - name: Download the tar.gz file
      get_url:
        url: "http://10.17.13.33/Harmonic/Rocky_Linux_8.8/XosRockyDependencies.tar.gz"
        dest: "/tmp/XosRockyDependencies.tar.gz"

    - name: Extract the tar.gz file
      unarchive:
        src: "/tmp/XosRockyDependencies.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Install all RPM files
      yum:
        name: "/tmp/XosRockyDependencies/*.rpm"
        state: present