- name: Make sure required packages are installed
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      dnf:
        name:
          - dnf-utils
          - net-tools
          - zip
          - unzip
          - ftp
          - wget
          - git
          - xauth
          - xterm
          - nfs-utils
          - epel-release
          - tcpdump
          - chrony
          - rsyslog
          - python3
          - htop
          - glances
          - nmon
        state: present

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes